#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.bash_functions" "$HOME/.bash_functions"
ln -sf "$PWD/.bash_aliases" "$HOME/.bash_aliases"
ln -sf "$PWD/.bash_dockerfunctions" "$HOME/.bash_dockerfunctions"
ln -sf "$PWD/.bash_completion" "$HOME/.bash_completion"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"

cp -r "$PWD/completion" "$HOME"
